### ISSUE TITLE
Problems with Piftfall.py

### ISSUE THREAD

**Issue by Antonioarf** [Antonioarf/trabalho_desoft#3]
************* Module Pitfall
src/Pitfall.py:1:0: C0303: Trailing whitespace (trailing-whitespace)
src/Pitfall.py:38:0: C0304: Final newline missing (missing-final-newline)
src/Pitfall.py:1:0: C0114: Missing module docstring (missing-module-docstring)
src/Pitfall.py:1:0: C0103: Module name "Pitfall" doesn't conform to snake_case naming style (invalid-name)
src/Pitfall.py:16:0: E1101: Module 'pygame' has no 'init' member (no-member)
src/Pitfall.py:27:4: C0103: Constant name "state" doesn't conform to UPPER_CASE naming style (invalid-name)
src/Pitfall.py:30:12: C0103: Constant name "state" doesn't conform to UPPER_CASE naming style (invalid-name)
src/Pitfall.py:34:12: C0103: Constant name "state" doesn't conform to UPPER_CASE naming style (invalid-name)
src/Pitfall.py:36:12: C0103: Constant name "state" doesn't conform to UPPER_CASE naming style (invalid-name)
src/Pitfall.py:38:4: E1101: Module 'pygame' has no 'quit' member (no-member)
src/Pitfall.py:3:0: C0411: standard import "import random" should be placed before "import pygame" (wrong-import-order)
src/Pitfall.py:4:0: C0411: standard import "import time" should be placed before "import pygame" (wrong-import-order)
src/Pitfall.py:7:0: C0411: standard import "from os import path" should be placed before "import pygame" (wrong-import-order)
src/Pitfall.py:3:0: W0611: Unused import random (unused-import)
src/Pitfall.py:4:0: W0611: Unused import time (unused-import)
src/Pitfall.py:7:0: W0611: Unused path imported from os (unused-import)
src/Pitfall.py:9:0: W0611: Unused GRAVITY imported from configuracoes (unused-import)

-----------------------------------
Your code has been rated at 0.00/10

**Comment by igordsm** [comment]
Isto já foi resolvido pelo PR aceito?

**Comment by Antonioarf** [comment]
Esqueci de fechar msm
